package srm573;
import java.util.*;

import static java.lang.Math.*;
import static java.lang.Integer.*;
import java.io.*;


// どうしてもTLE, MLEしちゃうんで、距離は保持しないで、次の更新点だけをsetで保持する似非ダイクストラに変更 
public class SkiResorts {

	long INF = Long.MAX_VALUE / 10;
	double DF = 0.0000000001;
	static PrintStream out = System.out;
	final int MOD = 1000000007;
	int N = 0;


	List<List<Integer>> G = null;

	long[][] dst = null;
	public long minCost(String[] r, int[] a){
		N = a.length;

		
		G = new ArrayList<List<Integer>>();
		for(int i = 0; i < N; i++){
			List<Integer> l = new ArrayList<Integer>();
			G.add(l);
		}
		for(int i = 0; i < r.length; i++){
			String s = r[i];
			for(int j = 0; j < s.length(); j++){
				if(s.charAt(j) == 'Y'){
					G.get(i).add(j);
				}
			}
		}
		dst = new long[N][N];
		for(int i = 0; i < N; i++){
			for(int j = 0; j < N; j++){
				dst[i][j] = INF;
			}
		}
		
		Set<Integer> que = new HashSet<Integer>();
		
		for(int i = 0; i < N; i++){
			dst[0][i] = abs(a[i] - a[0]);
			que.add(a(0, i));
		}
		
		while(que.size() > 0){
			Integer n = que.iterator().next();
			que.remove(n);
		
			int p = p(n);
			int h = h(n);
			
			for(int t : G.get(p)){
				for(int j = 0; j < N; j++){
					if(a[j] <= a[h]){
						long nd = dst[p][h] + abs(a[t] - a[j]);
						if(dst[t][j] > nd){
							dst[t][j] = nd;
							int nn = a(t, j);
							que.add(nn);	
						}
					}
				}				
			}
		}

		
		long ans = INF;
		for(int i = 0; i < N; i++){
			ans = min(ans, dst[N-1][i]);
		}
		if(ans == INF){
			return -1;
		}
		
		return ans;
	}
	
	int p(int a){
		return a % 100;
	}
	int h (int a){
		return a / 100;
	}
	int a(int p, int h){
		return h * 100 + p;
	}
	
	/**
	 * @param args
	 */
	public static void main(String[] args) {
		
		
		SkiResorts t = new SkiResorts();
		String[] r = {"NNYYYNNNYNYYNYYYYYNYYYYYNYYNYYNYYNNYYYNNNYYYYYYYYN", "NNYYYNYYYYYYNYNNYYYNYYYNYYYYYYYNYYYNYNYYNYYYYNYNYY", "YYNYNYYNYNYYNYYNYYYYYNYYYYYYNNNNYYYYNYYYNNYYYNNYNN", "YYYNNYYYYNYNYYYYYNNNNYNYNYYYNYYYYNNYYNNNYNYNYYNYYY", "YYNNNNYNNNYYYYYYYNNYYYNYYNYYNYYYNYNYYYYYYYYYYNYNNY", "NNYYNNNNNYYYYYNYNYYYNYYYYYYYNYYYYYYYYYYNYNYYYNYYNN", "NYYYYNNNYYYYYYNYYYNYYNYNYNNNYNYYYNYYNYYYYYYNNYYYNY", "NYNYNNNNYYYNYYYYYNYNYYYNYNYNYNYNNNYYNNNYNYYYYNYYYY", "YYYYNNYYNYNNYYYYYNNYYYNYNYNYNYYNYYNYYNYYYNNYNNNYNN", "NYNNNYYYYNNNNNYYYNNYNYYYYYNYNYNNNYYYYNYYYYYYYYNYNN", "YYYYYYYYNNNNNNYYYNYYNYNNYYNNNYYNYYYYYNYYYNYNNYYYYY", "YYYNYYYNNNNNNYNYYYNYNYNYYNYYYNYNYYNYNYNYYYYYNYYYNY", "NNNYYYYYYNNNNYNNYYYNYYYNYYYNYYNNYNYYYYYYYYYYNYYYYY", "YYYYYYYYYNNYYNNYYNYYNYYYYYYNYYYNYYYYNYNYYYNNYNNYYN", "YNYYYNNYYYYNNNNYYNNYYYYYNNNYNYYYYYYYNYYYYYYYYYYNYN", "YNNYYYYYYYYYNYYNNYYYYNNYYNYYNYNYYYYNYYNNNNNNYYNYNY", "YYYYYNYYYYYYYYYNNNYNYYNNYYYYYYYYYNNYYYYYNNNYNYYYYN", "YYYNNYYNNNNYYNNYNNYYYYYYYYYYYYNYNYYYYYYYYYYYNNYYYY", "NYYNNYNYNNYNYYNYYYNYYNYYYYNYYYNYYYYNYYNYNYYNYNNYNN", "YNYNYYYNYYYYNYYYNYYNYNNYYNNYNYYYYYYNYYYNYNNYYNNYNY", "YYYNYNYYYNNNYNYYYYYYNYYNNYYYYYYYNYNNYNYNYYNYYYNNYY", "YYNYYYNYYYYYYYYNYYNNYNYYYYYNNYNYNYNNYYNYYNNYNNYNYY", "YYYNNYYYNYNNYYYNNYYNYYNYNYNYNYNYYYYNYNYNYYYYNYYNYY", "YNYYYYNNYYNYNYYYNYYYNYYNNYYNYNNYYYYYYYNNNYNYYNYYYY", "NYYNYYYYNYYYYYNYYYYYNYNNNNNNYNYYYYYYNYNYYNYYYNYYYN", "YYYYNYNNYYYNYYNNYYYNYYYYNNNYNYYYNNNYYYNYYYYYYNYNYY", "YYYYYYNYNNNYYYNYYYNNYYNYNNNNYYYYYNNNNNYYYNYNYNYYYY", "NYYYYYNNYYNYNNYYYYYYYNYNNYNNYNNNNNYYYYYYYNYNYYYYNY", "YYNNNNYYNNNYYYNNYYYNYNNYYNYYNNNNYYYYYYYYYYNNYYYNNY", "YYNYYYNNYYYNYYYYYYYYYYYNNYYNNNNYYYYYYYYYYYYYNNYYYY", "NYNYYYYYYNYYNYYNYNNYYNNNYYYNNNNNNNYYYYNYNYYYYYYYYN", "YNNYYYYNNNNNNNYYYYYYYYYYYYYNNYNNYYYYNYYYYYYYYNYYYN", "YYYYNYYNYNYYYYYYYNYYNNYYYNYNYYNYNYYYYYYYYYYNNNYYYN", "NYYNYYNNYYYYNYYYNYYYYYYYYNNNYYNYYNNYYYYNYNNYNNYNYN", "NYYNNYYYNYYNYYYYNYYYNNYYYNNYYYYYYNNYNYYYNYYYYYNYNY", "YNYYYYYYYYYYYYYNYYNNNNNYYYNYYYYYYYYNNYYNYYYNYYNYYY", "YYNYYYNNYYYNYNNYYYYYYYYYNYNYYYYNYYNNNNYNYNYYYNYYNY", "YNYNYYYNNNNYYYYYYYYYNYNYYYNYYYYYYYYYNNYYYYYYNYYYNN", "NYYNYYYNYYYNYNYNYYNYYNYNNNYYYYNYYYYYYYNNNYNYYNYYYY", "NYYNYNYYYYYYYYYNYYYNNYNNYYYYYYYYYNYNNYNNYYNYNNYYNN", "NNNYYYYNYYYYYYYNNYNYYYYNYYYYYYNYYYNYYYNYNYYYYYYYNY", "YYNNYNYYNYNYYYYNNYYNYNYYNYNNYYYYYNYYNYYYYNYYYYYYNY", "YYYYYYYYNYYYYNYNNYYNNNYNYYYYNYYYYNYYYYNNYYNNNYYNYY", "YYYNYYNYYYNYYNYNYYNYYYYYYYNNNYYYNYYNYYYYYYNNYNYNNY", "YYYYYYNYNYNNNYYYNNYYYNNYYYYYYNYYNNYYYNYNYYNYNNYYYN", "YNNYNNYNNYYYYNYYYNNNYNYNNNNYYNYNNNYYNYNNYYYNNNNYYN", "YYNNYYYYNNYYYNYNYYNNNYYYYYYYYYYYYYNNYYYYYYYYYNNYNN", "YNYYNYYYYYYYYYNYYYYYNNNYYNYYNYYYYNYYYYYYYYNNYYYNYY", "YYNYNNNYNNYNYYYNYYNNYYYYYYYNNYYYYYNYNNYNNNYNYYNYNY", "NYNYYNYYNNYYYNNYNYNYYYYYNYYYYYNNNNYYYNYNYYYYNNNYYN"};
		int[] a ={16360756, 634016766, 667708796, 22536550, 430704709, 217998578, 991118700, 82196802, 50450957, 543510092, 65617767, 108183408, 49635627, 970716362, 997530109, 275116532, 551343819, 57179844, 932375282, 964653156, 1467467, 394717140, 490960707, 118632821, 911080004, 63458381, 209282180, 17599602, 294190616, 220201717, 896593804, 976728875, 946273827, 45662283, 65132275, 531107608, 334256346, 222707577, 131172200, 927097052, 701613757, 203471139, 785183776, 433292969, 217174007, 412409406, 935305807, 283671918, 427650549, 288760850};
		long ret = t.minCost(r, a);

		out.println(ret);

	}

}
